name: "Deploy Lambda"
description: "Deploy the Lambda Function"

inputs:
  AWS_ACCESS_KEY_ID:
    description: "Aws access key"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS secret"
    required: true
  AWS_REGION:
    description: "AWS region"
    required: true
  LAMBDA_FUNCTION_NAME:
    description: "Lambda function name"
    required: true
  LAMBDA_FUNCTION_ALIAS:
    description: "Lambda function alias"
    required: false
    default: ""
  artifact_name:
    description: "name of Image artifact (container) to deploy"
    required: true
  artifact_filename:
    description: "filename of Image artifact (container) to deploy"
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch Image URI artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}

    - name: Set variable image from artifact (image URI)
      shell: bash
      id: vars
      run: echo "image=$(cat ${{ inputs.artifact_filename }})" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Update the Lambda code (new Docker image)
      id: update_function
      shell: bash
      env:
        IMAGE_URI: ${{ steps.vars.outputs.image }}
        LAMBDA_FUNCTION_NAME: ${{ inputs.LAMBDA_FUNCTION_NAME }}
      run: |
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $IMAGE_URI
        aws lambda wait function-updated --function-name $LAMBDA_FUNCTION_NAME
        result=$(aws lambda publish-version --function-name $LAMBDA_FUNCTION_NAME)
        version=$(echo ${result}| jq -r .Version)
        echo "lambda_version=$version" >> $GITHUB_OUTPUT
        echo "Deployed version ${version} of the lambda $LAMBDA_FUNCTION_NAME"

    - name: Add or update Datadog environment variables
      id: datadog-env-vars
      shell: bash
      env:
        IMAGE_URI: ${{ steps.vars.outputs.image }}
        LAMBDA_FUNCTION_NAME: ${{ inputs.LAMBDA_FUNCTION_NAME }}
      run: |
        export EXTRACTED_VERSION=$(echo $IMAGE_URI | sed "s|.*:||g")
        UPDATED_ENVIRONMENT_VARIABLES=$(aws lambda get-function-configuration --function-name ${LAMBDA_FUNCTION_NAME} | \
          jq --compact-output ".Environment + {\"Variables\": (.Environment.Variables + {\"DD_VERSION\": env.EXTRACTED_VERSION, \"DD_GIT_COMMIT_SHA\": env.GITHUB_SHA })}")

        aws lambda update-function-configuration --function-name ${LAMBDA_FUNCTION_NAME} \
          --environment ${UPDATED_ENVIRONMENT_VARIABLES}

    - name: Update the Lambda Alias
      id: update_function_alias
      if: ${{ inputs.LAMBDA_FUNCTION_ALIAS != '' }}
      shell: bash
      env:
        LAMBDA_FUNCTION_VERSION: ${{ steps.update_function.lambda_version }}
        LAMBDA_FUNCTION_NAME: ${{ inputs.LAMBDA_FUNCTION_NAME }}
        LAMBDA_FUNCTION_ALIAS: ${{ inputs.LAMBDA_FUNCTION_ALIAS }}
      run: |
        aws lambda update-alias --function-name $LAMBDA_FUNCTION_NAME --name $LAMBDA_FUNCTION_ALIAS --function-version $LAMBDA_FUNCTION_VERSION
        echo "Alias updated"
