name: "Advance or create tag"
description: "Advance or create tag"

inputs:
  TAG_NAME:
    description: "Name of the tag"
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - name: Advance nightly tag
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}          
        script: |
          try {
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/${{ inputs.TAG_NAME }}"
              })
          } catch (e) {
            console.log("The ${{ inputs.TAG_NAME }} tag doesn't exist yet: " + e)
          }
          await github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ inputs.TAG_NAME }}",
            sha: context.sha
          })
