name: "Advance or create tag"
description: "Advance or create tag"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
  branch:
    description: The branch on which releases should happen
    default: "main"
    required: false

outputs:
  published:
    description: "Whether a new release was published. The return value is in the form of a string. ('true' or 'false')"
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  version:
    description: "New version released"
    value: ${{ steps.semantic-release.outputs.new_release_version }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: "Add package.json if missing"
      run: |
        FILE=package.json
        if ! [ -f "$FILE" ]; then
          echo '{' >> $FILE
          echo '"name": "@${{ github.repository }}",' >> $FILE
          echo '"version": "1.0.0",' >> $FILE
          echo '"private": true' >> $FILE
          echo '}' >> $FILE
        fi
      shell: bash

    - name: Semantic Release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        branches: |
          ["${{ inputs.branch }}"]
        branch: 'oldconf'
        dry_run: false
        extends: |
          @meero/github-actions-shared-workflows
        extra_plugins: |
          @semantic-release/commit-analyzer@9.0.2
          @semantic-release/release-notes-generator@10.0.3
          @semantic-release/changelog@6.0.1
          @semantic-release/github@8.0.6
          @semantic-release/git@10.0.1
          @semantic-release/exec@6.0.3
          conventional-changelog-conventionalcommits@4.3.0
          meero-com/github-actions-shared-workflows
