name: "Semantic release"
description: "Semantic release"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
  npm-token:
    description: The GitHub token used to create an authenticated client
    required: true
  branch:
    description: The branch on which releases should happen
    default: "main"
    required: false
  dry-run:
    description: Whether to run semantic release in dry-run mode
    default: false
    required: false

outputs:
  new_release_published:
    description: "Whether a new release was published ('true' or 'false')"
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  new_release_version:
    description: "Version of the new release"
    value: ${{ steps.semantic-release.outputs.new_release_version }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: "Add package.json if missing"
      run: |
        FILE=package.json
        if ! [ -f "$FILE" ]; then
          echo '{' >> $FILE
          echo '"name": "@${{ github.repository }}",' >> $FILE
          echo '"version": "1.0.0",' >> $FILE
          echo '"private": true' >> $FILE
          echo '}' >> $FILE
        fi
      shell: bash

    - name: Semantic Release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
      with:
        branches: |
          ["${{ inputs.branch }}"]
        branch: 'oldconf'
        dry_run: ${{ inputs.dry-run }}
        extends: |
          @meero/github-actions-shared-workflows
        extra_plugins: |
          @semantic-release/commit-analyzer@9.0.2
          @semantic-release/release-notes-generator@10.0.3
          @semantic-release/changelog@6.0.1
          @semantic-release/github@8.0.6
          @semantic-release/git@10.0.1
          @semantic-release/exec@6.0.3
          @semantic-release/npm@9.0.1
          conventional-changelog-conventionalcommits@4.3.0
          meero-com/github-actions-shared-workflows
