name: "Pull Docker image"
description: "Pull a Docker image from ECR and store it as artifact"

inputs:
  version:
    description: version short sha
    required: true
  artifact_name:
    description: Name for artifact (without extension)
    required: true
  AWS_ACCESS_KEY_ID:
    description: "Aws access key"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS secret"
    required: true
  ECR_REPOSITORY:
    description: "ECR repository"
    required: true
  AWS_REGION:
    description: "AWS region"
    required: true

outputs:
  artifact_name:
    description: "Image artifact name"
    value: ${{ inputs.artifact_name }}
  artifact_file_name:
    description: "Image artifact filename"
    value: ${{ inputs.artifact_name }}.tar
  image_tag:
    description: "Image tag"
    value: ${{ steps.image-current-tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Login to the Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: "Store Docker image URI"
      id: docker-uri
      shell: bash
      run: |
        echo "image-uri=$(echo ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.version }})" >> $GITHUB_OUTPUT

    - name: Pull Docker image from ECR
      shell: bash
      run: |
        docker pull ${{ steps.docker-uri.outputs.image-uri }}

    - name: Save Docker image as TAR
      shell: bash
      run: |
        mkdir -p /tmp/docker
        docker save --output /tmp/docker/${{ inputs.artifact_name }}.tar ${{ steps.docker-uri.outputs.image-uri }}

    - name: Save ImageURI as artifact_name.txt
      id: image-current-tag
      env:
        IMAGE_URI: ${{ steps.docker-uri.outputs.image-uri }}
      run: |
        echo "tag=$IMAGE_URI" >> $GITHUB_OUTPUT
      shell: bash

    - name: Save Image URI as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: /tmp/docker/${{ inputs.artifact_name }}.tar
