# Description:
#   This workflow check the build of the documentation and publish the result in a comment on the PR.
#   It can only be used for pull requests.
#
# Usage:
#
#   jobs:
#     build-documentation:
#       uses: meero-com/github-actions-shared-workflows/.github/workflows/build-documentation.yml@main

on:
  workflow_call:

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Action Disabled
        run: echo "🚫 This GitHub Action has been disabled and is no longer in use. See meero-com/github-actions-shared-workflows/.github/workflows/build-documentation.yml@main"
